apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selar-tls
  namespace: default
spec:
  secretName: selar-tls
  duration: 2160h    # 90 days
  renewBefore: 360h  # 15 days before expiry
  issuerRef:
    name: letsencrypt-prod-selar
    kind: ClusterIssuer
  commonName: selar.co
  dnsNames:
    - selar.co
