apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-selar
spec:
  acme:
    # Use the production ACME server
    server: https://acme-v02.api.letsencrypt.org/directory
    email: dozie@selar.co
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
      - http01:
          ingress:
            class: nginx
