apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: selar-app-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-selar
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - host: selar.co
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: selar-app-service
                port:
                  number: 80
  tls:
    - hosts:
        - selar.co
      secretName: selar-tls
